version: '3.1'
services:
  stats-server:
    build: ./explore-stat
    container_name: stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/explore-stat
      - SPRING_DATASOURCE_USERNAME=explore-stat
      - SPRING_DATASOURCE_PASSWORD=explore-stat
      - EXPLORE_REMOTE_SERVICE_URL=http://ewm-service:8080
    ports:
      - "9090:9090"
    depends_on:
      - stats-db

  stats-db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DATABASE=explore-stat
      - POSTGRES_USER=explore-stat
      - POSTGRES_PASSWORD=explore-stat
    ports:
      - "6543:5432"

  ewm-service:
    build: ./explore-main
    container_name: ewm-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/explore
      - SPRING_DATASOURCE_USERNAME=explore
      - SPRING_DATASOURCE_PASSWORD=explore
      - EXPLORE_REMOTE_SERVICE_URL=http://stats-server:9090
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - ewm-db

  ewm-db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DATABASE=explore
      - POSTGRES_USER=explore
      - POSTGRES_PASSWORD=explore
    ports:
      - "6542:5432"
