CREATE TABLE IF NOT EXISTS requests_count (
    request_id BIGINT,
    count BIGINT,
    CONSTRAINT pk_requests_count PRIMARY KEY (request_id)
);

CREATE TABLE IF NOT EXISTS statistics (
    statistic_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL ,
    request_id BIGINT,
    request_type VARCHAR(50) NOT NULL,
    client_ip VARCHAR(50) NOT NULL,
    request_date TIMESTAMP NOT NULL,
    CONSTRAINT pk_statistic PRIMARY KEY (statistic_id),
    CONSTRAINT fk_statistic_request_count FOREIGN KEY (request_id) REFERENCES requests_count (request_id)
);