CREATE TABLE IF NOT EXISTS statistics (
    statistic_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app_id VARCHAR(50) NOT NULL,
    endpoint VARCHAR(100) NOT NULL,
    client_ip VARCHAR(50) NOT NULL,
    request_date TIMESTAMP NOT NULL,
    CONSTRAINT pk_statistics PRIMARY KEY (statistic_id)
);